.catalog:
  name: "Redis"
  version: "3.0.7"
  description: "Redis is an open-source, networked, in-memory, key-value data store with optional durability. It is written in ANSI C."
  questions:
      - variable: "sentinel_down_after"
        label: "Default Down After"
        description: "The time (milliseconds) it takes to consider Redis Master is down."
        default: "300"
        required: true
        type: "int"
      - variable: "sentinel_failover_timeout"
        label: "Default Sentinel Failover Timeout"
        description: "The time (milliseconds) it takes takes to complete a failover in normal circunstances."
        required: true
        type: "int"
        default: "180000"
      - variable: "redis_slaves"
        label: "Default Number of Redis Slaves"
        description: "Number of Redis slaves"
        default: "2"
        required: true
        type: "int"
      - variable: "redis_sentinels"
        label: "Default Number of Redis Sentinels"
        description: "Number of Redis sentinels"
        default: "3"
        required: true
        type: "int"
redis-master:
  scale: 1
redis-slave:
  scale: ${redis_slaves}
redis-sentinel:
  scale: ${redis_sentinels}
