redis-master:
  image: redis:3
  labels:
    io.rancher.container.hostname_override: container_name
  ports:
    - "6379:6379"

redis-slave:
  image: redis:3
  labels:
    io.rancher.container.hostname_override: container_name
  command: redis-server --slaveof redis-master 6379
  links:
    - redis-master:redis-master
  ports:
    - "6379:6379"

redis-sentinel:
  image: hfreire/redis-sentinel
  labels:
    io.rancher.container.hostname_override: container_name
  environment:
    - SENTINEL_DOWN_AFTER=${sentinel_down_after}
    - SENTINEL_FAILOVER=${sentinel_failover_timeout}
  links:
    - redis-master:redis-master
    - redis-slave
  ports:
      - "26379:26379"
