flume:
  tty: true
  image: hfreire/flume:1.6.0
  environment:
    - CORE_CONF_fs_defaultFS=hdfs://hdfs:8020
    - FLUME_AGENT_NAME=${flume_agent_name}
    - FLUME_CONF_spark_master=
    - FLUME_CONF_${flume_agent_name}.sources=r1
    - FLUME_CONF_${flume_agent_name}.sinks=k1
    - FLUME_CONF_${flume_agent_name}.channels=c1
    - FLUME_CONF_${flume_agent_name}.sources.r1.type= org.apache.flume.source.http.HTTPSource
    - FLUME_CONF_${flume_agent_name}.sources.r1.port=9000
    - FLUME_CONF_${flume_agent_name}.sinks.k1.type=hdfs
    - FLUME_CONF_${flume_agent_name}.sinks.k1.hdfs.path=/dialogs/%{companyId}/%{userId}
    - FLUME_CONF_${flume_agent_name}.sinks.k1.hdfs.round=true
    - FLUME_CONF_${flume_agent_name}.sinks.k1.hdfs.roundValue=10
    - FLUME_CONF_${flume_agent_name}.sinks.k1.hdfs.roundUnit=minute
    - FLUME_CONF_${flume_agent_name}.channels.c1.type=memory
    - FLUME_CONF_${flume_agent_name}.channels.c1.capacity=1000
    - FLUME_CONF_${flume_agent_name}.channels.c1.transactionCapacity=100
    - FLUME_CONF_${flume_agent_name}.sources.r1.channels=c1
    - FLUME_CONF_${flume_agent_name}.sinks.k1.channel=c1
  external_links:
    - ${kafka_link}:kafka
    - ${hdfs_link}:hdfs
  labels: 
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
